
server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: USER-SERVICE
          uri: ${USER_SERVICE_ROUTE:lb://USER-SERVICE}
          predicates:
            - Path=/api/users/**, /api/auth/**

        - id: AI-JOURNAL
          uri: ${AI-JOURNAL_ROUTE:lb://AI-JOURNAL}
          predicates:
            - Path=/api/journals/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI}/eureka/

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.cloud.gateway: DEBUG

